"""Initial migration.

Revision ID: 59d81ab77347
Revises: 
Create Date: 2023-04-06 17:47:50.854202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d81ab77347'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info', sa.String(length=25), server_default='', nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=25),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('short_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_description', sa.VARCHAR(length=200), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('info')

    # ### end Alembic commands ###
